# WK 1 Homework

In [1]:
import pandas as pd

In [2]:
# Version check
pd.__version__

'3.0.6'

In [3]:
# read the dataset:
df = pd.read_csv('/workspaces/Datatalks-ml-zoomcamp/Week1/car_fuel_efficiency_2026.csv')
print(len(df))

10000

In [4]:
# coltypes
display(df.head())

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [ ]:
# Unique fuel types and their count
print(df['fuel_type'].unique())

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [6]:
# Missing data in columns
display(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

None

In [9]:
# Max fuel origin in Asia
print(df.loc[df['origin']=='Asia']['fuel_efficiency_mpg'].max())

41.2

## Median value of horsepower

In [11]:
# median before backfill
print(df['horsepower'].median())

# backfill - for this working with a copy
df_copy = df.copy(deep=True)
df_copy['horsepower'] = df_copy['horsepower'].fillna(df_copy['horsepower'].median())
print(df_copy['horsepower'].median())

254.0
254.0

## Matrix multiplication

In [14]:
all_asian_cars = df.loc[df['origin']=='Asia'] # all asian cars only
display(all_asian_cars.head(10))

# select only vehicle weight and model year
fmatrix = all_asian_cars[['vehicle_weight', 'model_year']].values
print(type(fmatrix))

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
16,2021,Asia,Gasoline,All-wheel drive,5,2280,6,234.0,4750,20.1,29.7
22,2019,Asia,Gasoline,Front-wheel drive,5,2350,6,246.0,4450,18.7,32.7
23,1994,Asia,Gasoline,Rear-wheel drive,4,2610,8,302.0,4440,17.1,26.6
25,2012,Asia,Diesel,Rear-wheel drive,2,2240,6,249.0,4210,18.0,33.8
31,1993,Asia,Gasoline,Front-wheel drive,5,2290,6,240.0,4230,18.7,28.0

<class 'numpy.ndarray'>

In [25]:
# matrix multiplication on the required subset
import numpy as np
fsubset = fmatrix[:7, :]
print(fsubset.shape)

# transpose
fsubset_T = np.transpose(fsubset)
print(fsubset_T.shape)

# Matrix multiplication
xtx = fsubset_T @ fsubset
print(xtx.shape)

# Invert xtx
xtx_inv = np.linalg.inv(xtx)
print(xtx.shape)

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

w = (xtx_inv @ fsubset_T) @ y
print(w.shape)
print(w.sum())

(7, 2)
(2, 7)
(2, 2)
(2, 2)
(2,)
0.36919696904925486